!set variable_substitution=true;
!define ver=V20;
--
use database &{db_name};
create schema if not exists &{sc_name};
--create schema &{sc_name};
use schema &{sc_name};
--
DROP PROCEDURE IF EXISTS DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN);
DROP PROCEDURE IF EXISTS DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN, BOOLEAN, VARCHAR);
DROP FUNCTION IF EXISTS REVENUE_SHARE(VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS REVENUE_SHARE(VARIANT, VARCHAR, FLOAT);
DROP FUNCTION IF EXISTS COLUMN_MAP(ARRAY);
DROP FUNCTION IF EXISTS DATA_PATTERN(ARRAY);
DROP TABLE IF EXISTS DATA_AGGREGATION_SOURCES;
DROP TABLE IF EXISTS DATA_AGGREGATION_TARGETS;
DROP TABLE IF EXISTS DATA_AGGREGATION_LOGGING;
--
ALTER TABLE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATION_TARGETS RENAME TO DATA_AGGREGATION_TARGETS;
ALTER TABLE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATION_SOURCES RENAME TO DATA_AGGREGATION_SOURCES;
ALTER TABLE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATION_LOGGING RENAME TO DATA_AGGREGATION_LOGGING;
ALTER FUNCTION IF EXISTS _BKBY_&{ver}_DATA_PATTERN(ARRAY) RENAME TO DATA_PATTERN;
ALTER FUNCTION IF EXISTS _BKBY_&{ver}_COLUMN_MAP(ARRAY) RENAME TO COLUMN_MAP;
ALTER FUNCTION IF EXISTS _BKBY_&{ver}_REVENUE_SHARE(VARIANT, VARCHAR, FLOAT) RENAME TO REVENUE_SHARE;
ALTER FUNCTION IF EXISTS _BKBY_&{ver}_REVENUE_SHARE(VARIANT, VARCHAR) RENAME TO REVENUE_SHARE;
ALTER PROCEDURE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN, BOOLEAN, VARCHAR) RENAME TO DATA_AGGREGATOR;
ALTER PROCEDURE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN) RENAME TO DATA_AGGREGATOR;
--
!set variable_substitution=false;
