!set variable_substitution=true;
!define ver=V13;
--
use database &{db_name};
use schema &{sc_name};
--!set variable_substitution=false;
--
-------------------------------------------------------
-- Remove installer created objects
-------------------------------------------------------
DROP PROCEDURE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN);
DROP PROCEDURE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN, BOOLEAN, VARCHAR);
DROP FUNCTION IF EXISTS &{db_name}.&{sc_name}.REVENUE_SHARE(VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS &{db_name}.&{sc_name}.REVENUE_SHARE(VARIANT, VARCHAR, FLOAT);
DROP FUNCTION IF EXISTS &{db_name}.&{sc_name}.COLUMN_MAP(ARRAY);
DROP FUNCTION IF EXISTS &{db_name}.&{sc_name}.DATA_PATTERN(ARRAY);
DROP TABLE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATION_SOURCES;
DROP TABLE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATION_TARGETS;
DROP TABLE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATION_LOGGING;
DROP SEQUENCE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATION_SOURCES_SEQ;
DROP SEQUENCE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATION_TARGETS_SEQ;
DROP SEQUENCE IF EXISTS &{db_name}.&{sc_name}.DATA_AGGREGATION_LOGGING_SEQ;
--
DROP PROCEDURE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN);
DROP PROCEDURE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATOR(VARCHAR, BOOLEAN, BOOLEAN, BOOLEAN, VARCHAR);
DROP FUNCTION IF EXISTS _BKBY_&{ver}_REVENUE_SHARE(VARIANT, VARCHAR);
DROP FUNCTION IF EXISTS _BKBY_&{ver}_REVENUE_SHARE(VARIANT, VARCHAR, FLOAT);
DROP FUNCTION IF EXISTS _BKBY_&{ver}_COLUMN_MAP(ARRAY);
DROP FUNCTION IF EXISTS _BKBY_&{ver}_DATA_PATTERN(ARRAY);
DROP TABLE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATION_SOURCES;
DROP TABLE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATION_TARGETS;
DROP TABLE IF EXISTS _BKBY_&{ver}_DATA_AGGREGATION_LOGGING;
--
--DROP SCHEMA IF EXISTS &{db_name}.&{sc_name} RESTRICT;
